.\"
.\" cinnamon₋settings-daemon manual page
.\" 
.\"
.TH CINNAMON-SETTINGS-DAEMON 1 "May 24 2013" ""
.SH NAME
cinnamon-settings-daemon \- Handles the CINNAMON session settings
.SH SYNOPSIS
\fBcinnamon-settings-daemon\fR [\fB\-\-debug\fR] [\fB\-\-no-daemon\fR]
[\fB\-\-gconf-prefix\fR] [\fB\-\-display\fR=\fIDISPLAY\fR]
.SH DESCRIPTION
\fIcinnamon-settings-daemon\fR is responsible for setting the various preference 
parameters of a CINNAMON session and the applications that run under it.
.SH OPTIONS
.PP
Help options
.TP
\-?, \fB\-\-help\fR
Show this help message
.PP
Application options
.TP 
\fB\-\^\-debug\fR
Enable debugging code
.TP
\fB\-\^\-no-daemon\fR
Do not detach the daemon process from its controlling terminal
.TP
\fB\-\^\-gconf-prefix\fR
Specify a custom GConf settings prefix for settings manager plugins
.TP
\fB\-\^\-display\fR=\fIDISPLAY\fR
X display to use
.PP

